# Generated by Django 3.1.2 on 2020-10-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('unique_squirrel_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('x', models.CharField(max_length=200)),
                ('y', models.CharField(max_length=200)),
                ('hectare', models.CharField(max_length=200)),
                ('Shift', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('hectare_squirrel_number', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('primary_fur_color', models.CharField(max_length=200)),
                ('highlight_fur_color', models.CharField(max_length=200)),
                ('combination_of_primary_and_highlight', models.CharField(max_length=200)),
                ('color_notes', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('above_ground_sighter_measurement', models.CharField(max_length=200)),
                ('specific_location', models.CharField(max_length=200)),
                ('running', models.CharField(max_length=200)),
                ('chasing', models.CharField(max_length=200)),
                ('climbing', models.CharField(max_length=200)),
                ('eating', models.CharField(max_length=200)),
                ('foraging', models.CharField(max_length=200)),
                ('other_activities', models.CharField(max_length=200)),
                ('kuks', models.CharField(max_length=200)),
                ('quaas', models.CharField(max_length=200)),
                ('moans', models.CharField(max_length=200)),
                ('tail_flags', models.CharField(max_length=200)),
                ('tail_twitches', models.CharField(max_length=200)),
                ('approaches', models.CharField(max_length=200)),
                ('indifferent', models.CharField(max_length=200)),
                ('runs_from', models.CharField(max_length=200)),
                ('other_interactions', models.CharField(max_length=200)),
                ('lat_long', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'squirrel',
                'verbose_name_plural': 'squirrel',
            },
        ),
    ]
