# Generated by Django 3.1.2 on 2020-10-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201021_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Shift',
            new_name='shift',
        ),
    ]
